<?php

use App\Http\Controllers\Api\AdminDashboardController;
use App\Http\Controllers\Api\AdminCultureTemplateController;
use App\Http\Controllers\Api\AdminCultureTemplateItemController;
use App\Http\Controllers\Api\CultureTemplateApplyController;
use App\Http\Controllers\Api\AdminDictionaryCategoryController;
use App\Http\Controllers\Api\AdminDictionaryEntryController;
use App\Http\Controllers\Api\AdminLessonTemplateController;
use App\Http\Controllers\Api\AdminModuleTemplateController;
use App\Http\Controllers\Api\AdminProgressReportController;
use App\Http\Controllers\Api\AdminQuizResultReportController;
use App\Http\Controllers\Api\AdminQuizTemplateController;
use App\Http\Controllers\Api\AdminQuizTemplateQuestionController;
use App\Http\Controllers\Api\AdminRegistrationRequestController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AvatarController;
use App\Http\Controllers\Api\ClassAssignmentController;
use App\Http\Controllers\Api\ClassLessonController;
use App\Http\Controllers\Api\ClassModuleController;
use App\Http\Controllers\Api\ClassQuizController;
use App\Http\Controllers\Api\DictionaryController;
use App\Http\Controllers\Api\DictionaryImportController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\ModuleTemplateApplyController;
use App\Http\Controllers\Api\PublicLookupController;
use App\Http\Controllers\Api\QuizAttemptController;
use App\Http\Controllers\Api\QuizQuestionController;
use App\Http\Controllers\Api\QuizReportController;
use App\Http\Controllers\Api\QuizTemplateApplyController;
use App\Http\Controllers\Api\ReportExportController;
use App\Http\Controllers\Api\SchoolClassController;
use App\Http\Controllers\Api\SchoolController;
use App\Http\Controllers\Api\StudentDashboardController;
use App\Http\Controllers\Api\StudentModuleController;
use App\Http\Controllers\Api\StudentProgressController;
use App\Http\Controllers\Api\StudentProgressReportController;
use App\Http\Controllers\Api\StudentQuizController;
use App\Http\Controllers\Api\StudentQuizResultReportController;
use App\Http\Controllers\Api\TeacherDashboardController;
use App\Http\Controllers\Api\TeacherProgressReportController;
use App\Http\Controllers\Api\TeacherQuizResultReportController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::prefix('public')->group(function () {
        Route::get('schools', [PublicLookupController::class, 'schools']);
        Route::get('schools/{school_id}/classes', [PublicLookupController::class, 'classes']);
        Route::get('media/{id}/content', [MediaController::class, 'publicContent']);
    });

    Route::prefix('auth')->group(function () {
        Route::post('register', [AuthController::class, 'register'])->middleware('throttle:emi-register');
        Route::post('login', [AuthController::class, 'login'])->middleware('throttle:emi-login');

        Route::middleware('auth:sanctum')->group(function () {
            Route::post('logout', [AuthController::class, 'logout']);
            Route::get('me', [AuthController::class, 'me']);
            Route::patch('me', [AuthController::class, 'updateProfile']);
            Route::put('password', [AuthController::class, 'updatePassword']);
            Route::post('me/avatar', [AvatarController::class, 'store']);
            Route::delete('me/avatar', [AvatarController::class, 'destroy']);
        });
    });

    Route::get('media/{id}/download', [MediaController::class, 'download'])
        ->name('media.download')
        ->middleware('signed:relative');

    Route::middleware(['auth:sanctum', 'role:admin'])->prefix('admin')->group(function () {
        Route::get('registration-requests', [AdminRegistrationRequestController::class, 'index']);
        Route::get('registration-requests/{id}', [AdminRegistrationRequestController::class, 'show']);
        Route::post('registration-requests/{id}/approve', [AdminRegistrationRequestController::class, 'approve']);
        Route::post('registration-requests/{id}/reject', [AdminRegistrationRequestController::class, 'reject']);
        Route::get('dashboard/summary', [AdminDashboardController::class, 'summary']);
        Route::get('reports/progress/schools', [AdminProgressReportController::class, 'schools']);
        Route::get('reports/progress/classes', [AdminProgressReportController::class, 'classes']);
        Route::get('reports/progress/students', [AdminProgressReportController::class, 'students']);
        Route::get('reports/quiz-results', [AdminQuizResultReportController::class, 'index']);
        Route::get('reports/progress/schools/export', [ReportExportController::class, 'adminSchools']);
        Route::get('reports/progress/classes/export', [ReportExportController::class, 'adminClasses']);
        Route::get('reports/progress/students/export', [ReportExportController::class, 'adminStudents']);
        Route::get('reports/quiz-results/export', [ReportExportController::class, 'adminQuizResults']);
        Route::get('dictionary/categories', [AdminDictionaryCategoryController::class, 'index']);
        Route::post('dictionary/categories', [AdminDictionaryCategoryController::class, 'store']);
        Route::get('dictionary/categories/{id}', [AdminDictionaryCategoryController::class, 'show']);
        Route::put('dictionary/categories/{id}', [AdminDictionaryCategoryController::class, 'update']);
        Route::delete('dictionary/categories/{id}', [AdminDictionaryCategoryController::class, 'destroy']);
        Route::get('dictionary/entries', [AdminDictionaryEntryController::class, 'index']);
        Route::post('dictionary/entries', [AdminDictionaryEntryController::class, 'store']);
        Route::get('dictionary/entries/{id}', [AdminDictionaryEntryController::class, 'show']);
        Route::put('dictionary/entries/{id}', [AdminDictionaryEntryController::class, 'update']);
        Route::delete('dictionary/entries/{id}', [AdminDictionaryEntryController::class, 'destroy']);
        Route::get('dictionary/imports/template', [DictionaryImportController::class, 'template']);
        Route::post('dictionary/imports/preview', [DictionaryImportController::class, 'preview']);
        Route::get('dictionary/imports', [DictionaryImportController::class, 'index']);
        Route::get('dictionary/imports/{id}', [DictionaryImportController::class, 'show']);
        Route::get('dictionary/imports/{id}/errors', [DictionaryImportController::class, 'errors']);
        Route::post('dictionary/imports/{id}/confirm', [DictionaryImportController::class, 'confirm']);
        Route::get('module-templates', [AdminModuleTemplateController::class, 'index']);
        Route::post('module-templates', [AdminModuleTemplateController::class, 'store']);
        Route::get('module-templates/{id}', [AdminModuleTemplateController::class, 'show']);
        Route::put('module-templates/{id}', [AdminModuleTemplateController::class, 'update']);
        Route::delete('module-templates/{id}', [AdminModuleTemplateController::class, 'destroy']);
        Route::post('module-templates/{id}/publish', [AdminModuleTemplateController::class, 'publish']);
        Route::post('module-templates/{id}/archive', [AdminModuleTemplateController::class, 'archive']);
        Route::post('module-templates/{id}/apply', ModuleTemplateApplyController::class);
        Route::get('module-templates/{module_template_id}/lessons', [AdminLessonTemplateController::class, 'index']);
        Route::post('module-templates/{module_template_id}/lessons', [AdminLessonTemplateController::class, 'store']);
        Route::patch('module-templates/{id}/lessons/reorder', [AdminLessonTemplateController::class, 'reorder']);
        Route::get('lesson-templates/{id}', [AdminLessonTemplateController::class, 'show']);
        Route::put('lesson-templates/{id}', [AdminLessonTemplateController::class, 'update']);
        Route::delete('lesson-templates/{id}', [AdminLessonTemplateController::class, 'destroy']);
        Route::post('lesson-templates/{id}/publish', [AdminLessonTemplateController::class, 'publish']);
        Route::post('lesson-templates/{id}/archive', [AdminLessonTemplateController::class, 'archive']);
        Route::get('quiz-templates', [AdminQuizTemplateController::class, 'index']);
        Route::post('quiz-templates', [AdminQuizTemplateController::class, 'store']);
        Route::get('quiz-templates/{id}', [AdminQuizTemplateController::class, 'show']);
        Route::put('quiz-templates/{id}', [AdminQuizTemplateController::class, 'update']);
        Route::delete('quiz-templates/{id}', [AdminQuizTemplateController::class, 'destroy']);
        Route::post('quiz-templates/{id}/publish', [AdminQuizTemplateController::class, 'publish']);
        Route::post('quiz-templates/{id}/archive', [AdminQuizTemplateController::class, 'archive']);
        Route::post('quiz-templates/{id}/apply', QuizTemplateApplyController::class);
        Route::get('quiz-templates/{quiz_template_id}/questions', [AdminQuizTemplateQuestionController::class, 'index']);
        Route::post('quiz-templates/{quiz_template_id}/questions', [AdminQuizTemplateQuestionController::class, 'store']);
        Route::patch('quiz-templates/{id}/questions/reorder', [AdminQuizTemplateQuestionController::class, 'reorder']);
        Route::get('quiz-template-questions/{id}', [AdminQuizTemplateQuestionController::class, 'show']);
        Route::put('quiz-template-questions/{id}', [AdminQuizTemplateQuestionController::class, 'update']);
        Route::delete('quiz-template-questions/{id}', [AdminQuizTemplateQuestionController::class, 'destroy']);
        Route::get('culture-templates', [AdminCultureTemplateController::class, 'index']);
        Route::post('culture-templates', [AdminCultureTemplateController::class, 'store']);
        Route::get('culture-templates/{id}', [AdminCultureTemplateController::class, 'show']);
        Route::put('culture-templates/{id}', [AdminCultureTemplateController::class, 'update']);
        Route::delete('culture-templates/{id}', [AdminCultureTemplateController::class, 'destroy']);
        Route::post('culture-templates/{id}/publish', [AdminCultureTemplateController::class, 'publish']);
        Route::post('culture-templates/{id}/apply', CultureTemplateApplyController::class);
        Route::post('culture-templates/{culture_template_id}/items', [AdminCultureTemplateItemController::class, 'store']);
        Route::get('culture-template-items/{id}', [AdminCultureTemplateItemController::class, 'show']);
        Route::put('culture-template-items/{id}', [AdminCultureTemplateItemController::class, 'update']);
        Route::delete('culture-template-items/{id}', [AdminCultureTemplateItemController::class, 'destroy']);
    });

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('schools', [SchoolController::class, 'index']);
        Route::post('schools', [SchoolController::class, 'store']);
        Route::get('schools/{id}', [SchoolController::class, 'show']);
        Route::put('schools/{id}', [SchoolController::class, 'update']);
        Route::delete('schools/{id}', [SchoolController::class, 'destroy']);
        Route::get('classes', [SchoolClassController::class, 'index']);
        Route::post('classes', [SchoolClassController::class, 'store']);
        Route::get('classes/{id}', [SchoolClassController::class, 'show']);
        Route::put('classes/{id}', [SchoolClassController::class, 'update']);
        Route::delete('classes/{id}', [SchoolClassController::class, 'destroy']);
        Route::post('classes/{id}/assign-teacher', [ClassAssignmentController::class, 'assignTeacher']);
        Route::post('classes/{id}/assign-student', [ClassAssignmentController::class, 'assignStudent']);
        Route::get('classes/{id}/students', [SchoolClassController::class, 'students']);
        Route::get('users', [UserController::class, 'index']);
        Route::get('users/{id}', [UserController::class, 'show']);
        Route::put('users/{id}', [UserController::class, 'update']);
        Route::patch('users/{id}/status', [UserController::class, 'updateStatus']);
        Route::post('media', [MediaController::class, 'store']);
        Route::get('media/{id}', [MediaController::class, 'show']);
        Route::post('media/{id}/temporary-url', [MediaController::class, 'temporaryUrl']);
        Route::delete('media/{id}', [MediaController::class, 'destroy']);
        Route::get('dictionary', [DictionaryController::class, 'index']);
        Route::get('dictionary/{id}', [DictionaryController::class, 'show']);
        Route::get('classes/{class_id}/modules', [ClassModuleController::class, 'index']);
        Route::post('classes/{class_id}/modules', [ClassModuleController::class, 'store']);
        Route::patch('classes/{class_id}/modules/reorder', [ClassModuleController::class, 'reorder']);
        Route::get('class-modules/{id}', [ClassModuleController::class, 'show']);
        Route::put('class-modules/{id}', [ClassModuleController::class, 'update']);
        Route::delete('class-modules/{id}', [ClassModuleController::class, 'destroy']);
        Route::post('class-modules/{id}/publish', [ClassModuleController::class, 'publish']);
        Route::post('class-modules/{id}/archive', [ClassModuleController::class, 'archive']);
        Route::get('class-modules/{class_module_id}/lessons', [ClassLessonController::class, 'index']);
        Route::post('class-modules/{class_module_id}/lessons', [ClassLessonController::class, 'store']);
        Route::patch('class-modules/{id}/lessons/reorder', [ClassLessonController::class, 'reorder']);
        Route::get('class-lessons/{id}', [ClassLessonController::class, 'show']);
        Route::put('class-lessons/{id}', [ClassLessonController::class, 'update']);
        Route::delete('class-lessons/{id}', [ClassLessonController::class, 'destroy']);
        Route::post('class-lessons/{id}/publish', [ClassLessonController::class, 'publish']);
        Route::post('class-lessons/{id}/archive', [ClassLessonController::class, 'archive']);
        Route::get('class-lessons/{id}/content-url', [ClassLessonController::class, 'contentUrl']);
        Route::get('class-quizzes', [ClassQuizController::class, 'index']);
        Route::post('class-quizzes', [ClassQuizController::class, 'store']);
        Route::get('class-quizzes/{id}', [ClassQuizController::class, 'show']);
        Route::put('class-quizzes/{id}', [ClassQuizController::class, 'update']);
        Route::delete('class-quizzes/{id}', [ClassQuizController::class, 'destroy']);
        Route::post('class-quizzes/{id}/publish', [ClassQuizController::class, 'publish']);
        Route::post('class-quizzes/{id}/archive', [ClassQuizController::class, 'archive']);
        Route::get('class-quizzes/{class_quiz_id}/questions', [QuizQuestionController::class, 'index']);
        Route::post('class-quizzes/{class_quiz_id}/questions', [QuizQuestionController::class, 'store']);
        Route::patch('class-quizzes/{id}/questions/reorder', [QuizQuestionController::class, 'reorder']);
        Route::get('quiz-questions/{id}', [QuizQuestionController::class, 'show']);
        Route::put('quiz-questions/{id}', [QuizQuestionController::class, 'update']);
        Route::delete('quiz-questions/{id}', [QuizQuestionController::class, 'destroy']);
        Route::post('class-quizzes/{id}/attempts', [QuizAttemptController::class, 'start'])->middleware('role:student');
        Route::get('class-quizzes/{id}/attempts', [QuizAttemptController::class, 'indexForQuiz']);
        Route::get('class-quizzes/{id}/report', [QuizReportController::class, 'show']);
        Route::get('quiz-attempts/{id}', [QuizAttemptController::class, 'show']);
        Route::put('quiz-attempts/{id}/answers/{question_id}', [QuizAttemptController::class, 'saveAnswer'])->middleware('role:student');
        Route::post('quiz-attempts/{id}/submit', [QuizAttemptController::class, 'submit'])->middleware('role:student');
    });

    Route::middleware(['auth:sanctum', 'role:student'])->prefix('student')->group(function () {
        Route::get('dashboard/summary', [StudentDashboardController::class, 'summary']);
        Route::get('reports/progress', [StudentProgressReportController::class, 'show']);
        Route::get('reports/quiz-results', [StudentQuizResultReportController::class, 'index']);
        Route::get('modules', [StudentModuleController::class, 'index']);
        Route::get('modules/{id}', [StudentModuleController::class, 'show']);
        Route::post('modules/{id}/start', [StudentModuleController::class, 'start']);
        Route::patch('lessons/{id}/progress', [StudentProgressController::class, 'updateLesson']);
        Route::get('progress/modules', [StudentProgressController::class, 'modules']);
        Route::get('quizzes', [StudentQuizController::class, 'index']);
        Route::get('quizzes/{id}', [StudentQuizController::class, 'show']);
    });

    Route::middleware(['auth:sanctum', 'role:teacher'])->prefix('teacher')->group(function () {
        Route::get('dashboard/summary', [TeacherDashboardController::class, 'summary']);
        Route::get('reports/progress/students', [TeacherProgressReportController::class, 'students']);
        Route::get('reports/quiz-results', [TeacherQuizResultReportController::class, 'index']);
        Route::get('reports/progress/students/export', [ReportExportController::class, 'teacherStudents']);
        Route::get('reports/quiz-results/export', [ReportExportController::class, 'teacherQuizResults']);
    });
});
